[package]
name = "flappybust"
version = "0.13.1"
edition = "2021"

[dependencies]
rand = "0.8.5"
itertools = "0.12.1"

[dependencies.strum]
version = "0.26.2"
features = ["derive"]

[dependencies.bevy]
version = "0.13.1"

[dependencies.bevy_asset_loader]
version = "0.20"
features = ["2d"]
