[alias]
watch_dynamic = "watch -i assets -cx run --features bevy/dynamic"
run_wasm = "run --target wasm32-unknown-unknown"

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=/opt/homebrew/bin/zld",
    "-Zshare-generics=y",
]

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[profile.dev]
debug = 1
